// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Infra.Persistence.Entity;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace Infra.Persistence.Context { 

public partial class MedicalClinicSystemContext : DbContext
{
    public MedicalClinicSystemContext()
    {
    }

    public MedicalClinicSystemContext(DbContextOptions<MedicalClinicSystemContext> options) : base(options)
    {
    }

    public virtual DbSet<MedicalAppointmentEntity> MedicalAppointments { get; set; }

    public virtual DbSet<PatientEntity> Patients { get; set; }

    // protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseSqlServer(builder.GetConnectionString("MedicalClinicDb"));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<MedicalAppointmentEntity>(entity =>
        {
            entity.HasOne(d => d.Patient)
                  .WithMany(p => p.Appointments)
                  .OnDelete(DeleteBehavior.ClientSetNull)
                  .HasConstraintName("FK_Medical_Appointment_Patients");
        });

        modelBuilder.Entity<PatientEntity>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.Gender).IsFixedLength();
            entity.HasMany(e => e.Appointments)
                  .WithOne(e => e.Patient)
                  .HasForeignKey(e => e.PatientId)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
}