// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Infra.Persistence.Entity;

[Table("Patients")]
public partial class PatientEntity
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("name")]
    [MaxLength(50)]
    public string Name { get; set; }

    [Required]
    [Column("mother_name")]
    [MaxLength(50)]
    public string MotherName { get; set; }

    [Column("date_of_birth", TypeName = "date")]
    public DateOnly DateOfBirth { get; set; }

    [Required]
    [Column("gender")]
    [StringLength(1)]
    [Unicode(false)]
    public Char Gender { get; set; }

    [Column("medication_allergy")]
    public bool? MedicationAllergy { get; set; }

    [Column("medication_allergy_description")]
    [MaxLength(256)]
    public string MedicationAllergyDescription { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Patient")]
    public virtual ICollection<MedicalAppointmentEntity> Appointments { get; set; } = new List<MedicalAppointmentEntity>();
}